### PR TITLE
CI: Add more Python versions

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by jonashaag** [comment]
@masatake please review

If you have ideas how to get the excluded combinations to work, that'd be helpful.

We could also skip some versions to keep CI smaller.

**Comment by masatake** [comment]
@jonashaag I don't know.

I think it is better to split the main.yml into smaller ones considering the differences in versions.

e.g. 3.4 looks like it requires special treatments.

In that case, we can move the statements related to 3.4 from main.yml to a new file called main-3-4.yml.

**Comment by sbraz** [comment]
> e.g. 3.4 looks like it requires special treatments.

Meh, we should just drop that version altogether, it's ancient. People who're stuck on Debian 8 or Ubuntu 14.04 can live with an older version of this package.

Debian 9 was released 5 years ago. Ubuntu 16.04 was released 6 years ago. Both of these ship Python 3.5 or newer.

**Comment by masatake** [comment]
This is just my opinion.
I think you have tired to do too many things in "CI: Add more Python versions".

You can improve the code more incrementally:
A. use tox directly instead of using make
B. delete travis.yml
C. run on mac
D. run on windows
E. add 3.4
F. add 2.7

You just call them "Add more Python versions".
How about solving A ~ D first in the original version set?
You can solve E. and F. after solving A ~ D.

About B, I should do it in my pull request. Sorry for taking your time.

I have no comment about the versions we should target because I'm too new in these areas both Python and Debian.

**Comment by jonashaag** [comment]
Thanks both for your feedback!

I dropped Python 3.4 because it makes CI more complicated and there's little reason to use Python 3.4.

I'd like to not spend more time on refactoring this PR so I'd like to merge it as is if the tests are green.

**Pull request merged**
