### PR TITLE
Use libreadtags

### PR DESCRIPTION
**Pull request by masatake**
A few years ago, I made a new repository specialized in readtags.[ch].
I added some new APIs to readtags.[ch] in the repository.
u-ctags uses the repository to build the readtags command that is part of u-ctags.
u-ctags uses 'git subtree' to pull in the latest libreadtags.
This pull request does the same for python-ctags3.

pull-libreadtags.sh the script for the maintainers of this project.

### CODE REVIEW

**Comment by jonashaag** [comment]
We don't need the entire libreadtags repo in here, just the `readtags.{c,h}` files

**Comment by masatake** [comment]
Pulling the files from the libreadtags repo. What kind of commands should we use?
Curl or wget?

In my experience in ctags, I found 'git subtree' is easy. So I used it in this pull request.

If we use another tool, I would like to have a shell script wrapping the tool to make pull-in readtags.[ch] easier. So I can make a pull request for python-ctags3 easily when I introduce important changes to libreadtags.

**Comment by masatake** [comment]
I found update-readtags target does the same.

**Comment by jonashaag** [comment]
Yeah I added this yesterday 😀

**Pull request closed without merging**
