### PR TITLE
add wrappers for PseudoTags related APIs

### PR DESCRIPTION
**Pull request by masatake**
Added the following methods:

```
    def firstPseudoTag(self, TagEntry entry):
        return ctagsFirstPseudoTag(self.file, &entry.c_entry)

    def findPseudoTag(self, TagEntry entry, char* name, int options):
        return ctagsFindPseudoTag(self.file, &entry.c_entry, name, options)

    def nextPseudoTag(self, TagEntry entry):
        return ctagsNextPseudoTag(self.file, &entry.c_entry)
```

### CODE REVIEW

**Review by jonashaag — APPROVED** [review]
`_` in Python is almost always used as a „throwaway“ name, so using it as an actual variable is confusing to Python readers.

**Comment by masatake** [comment]
> _ in Python is almost always used as a „throwaway“ name, so using it as an actual variable is confusing to Python readers.

Do you mean I should refine my pull request?
I used `_` in my pull request, but I did so to make my change similar to the code around the change. If we should not use `_` in the context, we must fix the whole code around my change. Such extensive refactoring is out of the scope of this pull request.

**Comment by jonashaag** [comment]
Oh ok didn’t look at the other code. Then let’s keep it.

**Comment by masatake** [comment]
When I get approval from you, should I merge my pull request? or will you merge it?

**Comment by jonashaag** [comment]
Yes feel free to merge!

**Comment by masatake** [comment]
I see.
I would like to merge this after merging #19.
Could you look at #19 and give me approval for #19?

**Comment by masatake** [comment]
Merged after rebasing on the master branch.

**Pull request merged**
